parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2020
  sourceType: module
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
rules:
  max-len:
    - error
    -
      code: 120
      tabWidth: 2
      ignoreComments: false
      ignoreStrings: false
  no-trailing-spaces:
    - error
  no-unused-vars:
    - warn
